=== HFCherish/performance-api/doc/schemas/response_200_get_users.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "count": {
      "type": "number"
    },
    "self": {
      "type": "string"
    },
    "first": {
      "type": "string"
    },
    "last": {
      "type": "string"
    },
    "prev": {
      "type": "string"
    },
    "next": {
      "type": "string"
    },
    "items": {
      "type": "array",
      "items": "object",
      "properties": {
        "username": {
          "type": "string"
        },
        "id": {
          "type": "number"
        },
        "email": {
        	"type": "string"
        },
        "links": {
          "type": "array",
          "items": "object",
          "properties": {
            "rel": {
              "type": "string"
            },
            "uri": {
              "type": "string"
            }
          },
          "required": [
            "rel",
            "uri"
          ]
        }
      },
      "required": [
        "id",
        "username",
        "email",
        "links"
      ]
    },
    "required": [
      "count",
      "self",
      "first",
      "last",
      "prev",
      "next",
      "items"
    ]
  }
}

=== HFCherish/performance-api/doc/examples/response_200_get_evidences.json
{
  "count": 10,
  "prev": "xx",
  "next": "xxx",
  "first": "xxx",
  "last": "xxx",
  "items": [
    {
      "id": "xxx",
      "content": "xxx",
      "createAt": 67586903678,
      "selfReflection": "xxx",
      "owner": {
        "username": "pzzheng",
        "nickname": "peizhen zheng",
        "id": "1",
        "email": "pzzheng@thoughtworks.com",
        "role": "Dev",
        "department": "Professional Services"
      },
      "observers": [
        {
          "id": "xx",
          "nickname": "xxx",
          "username": "xxx"
        }
      ],
      "links": {
        "self": "user/username/self_reflections/srid/evidences/eid",
        "self_reflection": "user/username/self_reflections/srid"
      },
      "behavior": {
        "id": "xxx",
        "name": "xxx",
        "description": "xxx",
        "hint": "xxx",
        "competence": {
          "id": "xxx",
          "name": "xxx",
          "description": "xxx",
          "category": {
            "id": "xxx",
            "name": "xxx"
          },
          "links": {
            "self": "competences/1"
          }
        }
      },
      "feedbacks": [
        {
          "id": "xxx",
          "author": {
            "username": "xxx",
            "nickname": "xxx"
          },
          "author_role": "coach | observer",
          "program": {
            "id": "xx",
            "name": "xxx"
          },
          "feedback_type": "endorse | comment",
          "comment": "xxx"
        }
      ]
    }
  ]
}

=== HFCherish/performance-api/doc/examples/response_200_get_programs.json
{
  "count": 10,
  "first": "xx",
  "last": "",
  "prev": "",
  "next": "",
  "items": [
    {
      "id": "xxx",
      "name": "",
      "description": "",
      "status": "PUBLISHED",
      "startDate": 789798787,
      "endDate": 7978768,
      "links": {
          "self": "programs/1"
      }
    }
  ]
}

=== HFCherish/performance-api/doc/examples/response_200_get_witness_invitations.json
{
  "count": 10,
  "prev": "xx",
  "next": "xxx",
  "first": "xxx",
  "last": "xxx",
  "items": [
    {
      "inviter": {
        "username": "pzzheng",
        "nickname": "peizhen zheng",
        "id": "1",
        "email": "pzzheng@thoughtworks.com",
        "role": "Dev",
        "department": "Professional Services"
      },
      "author": {
        "username": "pzzheng",
        "nickname": "peizhen zheng",
        "id": "1",
        "email": "pzzheng@thoughtworks.com",
        "role": "Dev",
        "department": "Professional Services"
      },
      "id": "invitation id",
      "author_role": "COACH | OBSERVER",
      "program": {
        "id": "xxx",
        "name": "xxx"
      },
      "evidence": {
        "id": "xxx",
        "content": "his evidence",
        "createdAt": 1476347270
      },
      "behavior": {
        "id": "xxx",
        "name": "name",
        "description": "xxx",
        "hint": "xxx",
        "competence": {
          "id": "xxx",
          "name": "self confidence",
          "description": "a...",
          "category": {
            "id": "xxx",
            "name": "core competence"
          },
          "links": {
            "self": "competences/1"
          }
        }
      },
      "links": [
        {
          "rel": "self",
          "uri": "/users/uxxx/self_reflections/xxx/evidences/xxx/feedbacks"
        },
        {
          "rel": "evidence",
          "uri": "/users/uxxx/self_reflections/xxx/evidences/xxx"
        }
      ]
    }
  ]
}

=== HFCherish/performance-api/doc/examples/response_200_get_self_reviews.json
{
  "count": 10,
  "prev": "xx",
  "next": "xxx",
  "first": "xxx",
  "last": "xxx",
  "items": [
    {
      "id": "xxx",
      "createdAt": 123123123,
      "owner": "pzzheng",
      "creator": "username who create the self reflection. can be coach name",
      "links": [
        {
          "rel": "self",
          "uri": "/users/pzzheng/programs/1/self_reviews/1"
        }
      ],
      "program": {
          "id": "xxx",
          "name": "xx",
          "description": "xx",
          "status": "PUBLISHED",
          "startDate": 789798787,
          "endDate": 7978768
      },
      "competences": [
        {
          "id": "xx",
          "name": "xxx",
          "description": "desc...",
          "category": {
            "id": "xx",
            "name": "xxx"
          },
          "behaviors": [
            {
              "id": "xxx",
              "description": "xxx",
              "grade": "CON",
              "hint": "xxx",
              "role": "PM | DEV"
            }
          ]
        }
      ],
      "evidences": [
        {
          "id": "xxx"
        }
      ]
    }
  ]
}

=== HFCherish/performance-api/doc/examples/response_200_get_self_reflections.json
{
  "count": 10,
  "prev": "xx",
  "next": "xxx",
  "first": "xxx",
  "last": "xxx",
  "items": [
    {
      "id": "xxx",
      "createdAt": 123123123,
      "owner": "coachee name",
      "creator": "username who create the self reflection. can be coach name",
      "behaviors": [{
        "id": "xxx",
        "name": "xxx",
        "description": "xxx",
        "hint": "xxx",
        "competence": {
          "id": "xxx",
          "name": "xxx",
          "description": "xxx",
          "category": {
            "id": "xxx",
            "name": "xxx"
          }
        }
      }],
      "evidences": [
        {
          "id": "xxx"
        }
      ]
    }
  ]
}
